name: Test
on:
  workflow_dispatch:

jobs:
  androidTest:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      
      
      - name: Setup local.properties
        run: touch ./local.properties
      
      - name: Make files executable
        run: chmod +x ./app/src/main/cpp/x86.sh
        
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        env:
          FABRIC_API_KEY: ${{ secrets.FABRIC_API_KEY }}
          FABRIC_API_SECRET: ${{ secrets.FABRIC_API_SECRET }}
         # NDK_ROOT: /usr/local/lib/android/sdk/ndk-bundle
          NDK_ROOT: /Users/runner/Library/Android/sdk/ndk-bundle
           #(Expected '/usr/local/lib/android/sdk/ndk/21.4.7075529')

        with:
          api-level: 28
          arch: x86
          disable-animations: true
          
          script: cd ./app/src/test/cpp && ../../main/cpp/x86.sh
          #script: cd ./app/src/main/cpp && ./x86.sh
          #script: ./gradlew connectedCheck --stacktrace
          
